Use proper way of retrieving admin-ajax.php URL
easydigitaldownloads/edd-resend-receipt pull request #13
Opened 2021-06-22 17:12 UTC by dimadin

2021-06-22 21:28 UTC, robincornett requested changes
I think it would be better, please, to remove this hidden input and add the ajax URL to the localized script variables defined in `edd_resend_receipt_scripts`. It looks like EDD has a helper function to get the ajax URL (`edd_get_ajax_url()`, since 1.3 so it should be okay to use, I think).

I'm not sure why this function has the `include_once` that it does on line 84... I know this isn't what you are working on but I wonder if we can remove it? It makes me uncomfortable.

2021-06-22 22:11 UTC, dimadin commented
> I think it would be better, please, to remove this hidden input and add the ajax URL to the localized script variables defined in `edd_resend_receipt_scripts`. It looks like EDD has a helper function to get the ajax URL (`edd_get_ajax_url()`, since 1.3 so it should be okay to use, I think).

Done!

> I'm not sure why this function has the `include_once` that it does on line 84... I know this isn't what you are working on but I wonder if we can remove it? It makes me uncomfortable.

It's there for a reason, see 29d1741bef604648b6624abaca95ce987e62a313. `is_plugin_active()` is defined in that file. Though querying by license doesn't even work, see #9.

2021-06-23 12:08 UTC, ashleyfae requested changes

2021-06-23 12:08 UTC, ashleyfae commented on includes/scripts.php
> +	wp_enqueue_script( 'ajax_submission', EDD_RESEND_RECEIPT_URL . '/assets/js/ajax_req' . $suffix . '.js', array( 'jquery' ), '1.0.2', true );
```suggestion
	wp_enqueue_script( 'ajax_submission', EDD_RESEND_RECEIPT_URL . '/assets/js/ajax_req' . $suffix . '.js', array( 'jquery' ), EDD_RESEND_RECEIPT_VER, true );
```

That constant is the current version number. Better than hard-coding it, because we'd definitely forget to change it at some point. :sweat_smile:

2021-06-23 20:51 UTC, robincornett approved these changes

2021-06-28 13:38 UTC, ashleyfae approved these changes

2021-06-28 13:38 UTC, merged